#
# Module manifest for module 'LeBlancCodes.PowerShell.Utilities'
#
# Generated by: LeBlanc Codes, LLC
#
# Generated on: 1/8/2018
#

@{
  RootModule = 'LeBlancCodes.PowerShell.Utilities.dll'
  ModuleVersion = '1.0.0.0'
  GUID = '04413b35-b0cc-438b-8ea9-29885fc97427'
  Author = 'Joachim Brandon LeBlanc'
  CompanyName = 'LeBlanc Codes, LLC'
  Copyright = 'Copyright (C) 2018 LeBlanc Codes, LLC'
  Description = 'A collection of PowerShell utilities.'
  PowerShellVersion = '4.0'
  DotNetFrameworkVersion = '4.6.2'
  RequiredAssemblies = @('Newtonsoft.Json.dll')
  CmdletsToExport = @(
    'Merge-Directories'
  )
  
  PrivateData = @{
    PSData = @{
      Tags = @('Utilities', 'PSModule')
      LicenseUri = 'https://github.com/demosdemon/LeBlancCodes.PowerShell.Utilities/blob/master/LICENSE'
      ProjectUri = 'https://github.com/demosdemon/LeBlancCodes.PowerShell.Utilities'
      ReleaseNotes = 'Initial Release'
    }
  }
}

